services:

  db-service: 
    container_name: SSA-db
    image: postgres:latest
    ports:
      - 5432:5432

    env_file:
      - ./ssa-db_params.env

    volumes: 
      - SSA_db_volume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-dbuser} -d $${POSTGRES_DB:-mydb} || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 5s


  # investigar un poco más redis y que necesita
  redis:
    container_name: redis-container
    image: redis:7-alpine
    ports: 
      - 6379:6379

  backend:

    container_name: ssa-backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    
    ports: 
      - 8080:8000

    command: uvicorn main:app --host 0.0.0.0 --port 8000

    env_file:
      - ./.env
    depends_on:
      db-service:
        condition: service_healthy

    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile 
        - action: sync+restart
          path: backend/src
          target: /app

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  frontend:
    image: nginx:alpine
    container_name: SSA-frontend
    ports:
      - "3000:80"
    volumes:
      - ./app/frontend/src:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/index.html"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped


volumes:
  SSA_db_volume:

